# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CreditChina' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'WLPlatform', :path => '../WLLib/WLPlatform'
pod 'WLControls', :path => '../WLControls/WLControls'
pod 'WLLogin_Category', :path => '../WLLogin_Category'
pod 'WLLogin', :path => '../WLLogin'

pod 'WLPublicity_Category', :path => '../WLPublicity_Category'
pod 'WLPublicity', :path => '../WLPublicity'

pod 'Masonry'
pod 'ProgressHUD'
pod 'MJExtension'
pod 'AFNetworking', '~> 3.0'
pod 'SDCycleScrollView','~> 1.75'
#pod 'SVGKit'


end
